
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Leftbar } from "@/Component/Leftbar";
import { FullContextProvider } from "@/Component/context";
import { useFullContext } from "@/Component/context";
import { Providerr } from "@/Component/Provider";
import { QueryClientProvider } from "@tanstack/react-query";
import { PersistGate } from "redux-persist/integration/react";
import { QueryClient } from "@tanstack/react-query";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const client = new QueryClient();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      
{/*    
        <QueryClientProvider client={client}>
        <FullContextProvider> */}
        <Providerr>
          {children}
          </Providerr>
          {/* </FullContextProvider>
          </QueryClientProvider> */}
        
     
        
      </body>
    </html>
  );
}
